version: '3.9'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    entrypoint: /load_db.sh
    depends_on: #links:
      - db
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app

  db: 
    image: mysql
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root